name: pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      ORGANISATION_NAME: aemdesign
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Experimental Status
        run: |
          docker version -f '{{.Server.Experimental}}'
      - name: Docker
        run: |
          docker version -f '{{.Server.Experimental}}'
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker version -f '{{.Server.Experimental}}'
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
          sudo rm /etc/docker/daemon.json
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - uses: actions/checkout@v2
      - name: set envirnment variables
        id: config
        run: |
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/github_get_config.sh)
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/github_get_version.sh)
      - name: build and test docker image
        run: |
          docker build --pull --squash -t $IMAGE:$GIT_BRANCH .
          (cd test && bash ./run_tests.sh "$IMAGE:$GIT_BRANCH")
          docker images

      - name: Run docker image analysis
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: ${{ env.IMAGE }}:${{ env.GIT_BRANCH }}
          config-file: ${{ env.GITHUB_WORKSPACE }}/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: login to docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${DOCKER_REGISTRY} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: push image version
        run: |
          docker push $IMAGE:$GIT_BRANCH
      - name: push latest image on main
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE:$GIT_BRANCH $IMAGE:latest
          docker push $IMAGE:latest


      - name: Update Docker Hub Description
        if: github.ref == 'refs/heads/main'
        run: |
          LOGIN_PAYLOAD="{\"username\": \"${DOCKER_USERNAME}\", \"password\": \"${DOCKER_PASSWORD}\"}"
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "${LOGIN_PAYLOAD}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          README_FILEPATH=${README_FILEPATH:="./README.md"}
          README_CONTENT=$(cat $README_FILEPATH)
          README_CONTENT_JSON=$(jq -n --arg CONTENT "$README_CONTENT" '{"full_description": "\($CONTENT)"}' )
          REPO_URL="https://hub.docker.com/v2/repositories/aemdesign/pnpm/"
          curl -vvvL -H "Authorization: JWT ${TOKEN}" -H "Content-Type: application/json" -X PATCH  --data "$README_CONTENT_JSON" ${REPO_URL}

      - uses: meeDamian/github-release@2.0
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.GITHUB_TAG }}
          name: ${{ env.GITHUB_TAG }}
          body: ${{ env.GIT_RELEASE_NOTES }}
